FROM debian:bookworm-slim AS builder

WORKDIR /node

COPY . .

RUN apt-get update && apt-get install -y \
    curl git build-essential ca-certificates \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    gcc-multilib g++-multilib libc6-dev-i386 \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    curl git build-essential ca-certificates \
    gcc libc6-dev-i386 \
    libssl3 iproute2 procps \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    libssl3 \
    iproute2 \
    curl \
    procps \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN git config --global http.sslVerify false

RUN curl https://nim-lang.org/download/nim-2.2.10-linux_x64.tar.xz -o /tmp/nim.tar.xz \
    && tar -xf /tmp/nim.tar.xz -C /tmp \
    && cp -r /tmp/nim-2.2.10/* /usr/local \
    && rm -rf /usr/local/nim* && mv /tmp/nim-2.2.10 /usr/local/nim-2.2.10

RUN nimble refresh

RUN ln -sf /usr/local/nim-2.2.10/bin/nim /usr/local/bin/nim
RUN ln -sf /usr/local/nim-2.2.10/bin/nimble /usr/local/bin/nimble
RUN ln -sf /usr/local/nim-2.2.10/bin/nim /usr/local/bin/nimcheck

RUN echo 'import strutils; echo "OK"' > temp.nim && nim r temp.nim && rm temp.nim

RUN nim --version
RUN nimble --version
RUN nimble install -dy --verbose | tee /tmp/install.log && grep -A 20 "libp2p" /tmp/install.log | grep -oP '\b\d+\.\d+\.\d+\b' | head -n1 > ./libp2p_version

RUN nimble c \
    --os:linux --cpu:amd64 --passL:"-static -mmusl" \
    -d:chronicles_colors=None --threads:on --mm:refc \
    -d:metrics -d:libp2p_network_protocols_metrics -d:release -d:pubsubpeer_queue_metrics \
    -d:libp2p_expensive_metrics -d:libp2p_agents_metrics \
    --passL:"-static-libgcc -static-libstdc++" \
    main

RUN chmod +x /node/main
RUN nim --version > nim_version
RUN nimble --version > nimble_version

EXPOSE 5000 8008 8645

ENTRYPOINT ["/node/main"]